from pathlib import Path
import shutil
import utils
import plotting
import numpy as np
import xs


class P58Problem:
    def __init__(self, workdir, nprocs=2, ntrain=100, ntest=10, random_seed=None):
        self.workdir = Path(workdir)
        self.deck_path = self.workdir / "base_P58.py"

        self.nprocs = nprocs
        self.ntrain = ntrain
        self.ntest = ntest
        self.rng = np.random.default_rng(random_seed)

        self.xs = xs.CrossSections(
            [
                {
                    "in_file": str(self.workdir / "URRb_base.xs"),
                    "out_file": str(self.workdir / "data" / "URRb.xs"),
                    "kind": "fission",
                },
            ],
            frac=0.2,
            transfer_tol=1.0e-14
        )

    def prepare_inputs(self):
        """Stage inputs that are not generated by the parameterization."""
        data_dir = self.workdir / "data"
        data_dir.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(
            self.workdir / "H2O_mg_base.xs",
            data_dir / "H2O_mg.xs",
        )

    def sample_training(self):
        self.prepare_inputs()
        lhs_seed = int(self.rng.integers(0, np.iinfo(np.uint32).max))
        self.training_set = utils.sample_LHS(
            self.xs.bounds, self.ntrain, seed=lhs_seed
        )

        params_path = self.workdir / "data" / "params.txt"
        np.savetxt(str(params_path), self.training_set)

    def load_training(self):
        params_path = self.workdir / "data" / "params.txt"
        self.training_set = np.loadtxt(str(params_path))

    def sample_testing(self):
        self.testing_set = utils.sample_test(
            self.xs.bounds, self.ntest, rng=self.rng
        )

        params_path = self.workdir / "data" / "test_params.txt"
        np.savetxt(str(params_path), self.testing_set)

    def update_xs(self, pvec):
        self.xs.write_sample(pvec)

    def plot_results(self, include_mipod=False):
        plotting.plot_sv(num_groups=2)
        errors = []
        k_errors = []
        speedups = []
        mi_errors = []
        mi_k_errors = []
        mi_speedups = []
        for i in range(self.ntest):
            results_dir = self.workdir / "results"
            rom_time = np.loadtxt(str(results_dir / "online_time_{}.txt".format(i)))
            if include_mipod:
                mi_time = np.loadtxt(str(results_dir / "mipod_time_{}.txt".format(i)))
            fom_time = np.loadtxt(str(results_dir / "offline_time_{}.txt".format(i)))

            output_dir = self.workdir / "output"
            error = plotting.plot_1d_eigenvector(
                str(output_dir / ("fom_{}_".format(i) + "{}.h5")),
                str(output_dir / ("rom_{}_".format(i) + "{}.h5")),
                ranks=range(self.nprocs),
                pid=i)
            k_error = np.abs(
                np.loadtxt("output/test_fom_k_{}.txt".format(i))
                - np.loadtxt("output/rom_k_{}.txt".format(i))
            )

            if include_mipod:
                mi_error = plotting.plot_1d_eigenvector(
                    str(output_dir / ("fom_{}_".format(i) + "{}.h5")),
                    str(output_dir / ("mipod_{}_".format(i) + "{}.h5")),
                    ranks=range(self.nprocs),
                    pid=i)
                mi_k_error = np.abs(
                    np.loadtxt("output/test_fom_k_{}.txt".format(i))
                    - np.loadtxt("output/mipod_k_{}.txt".format(i))
                )

            k_errors.append(k_error)
            errors.append(error)
            speedups.append(fom_time / rom_time)

            if include_mipod:
                mi_k_errors.append(mi_k_error)
                mi_errors.append(mi_error)
                mi_speedups.append(fom_time / mi_time)

        print("Avg Eigenvector Error ", np.mean(errors))
        np.savetxt("results/errors.txt", errors)
        print("Avg k Error ", np.mean(k_errors) * 1e5, "pcm")
        np.savetxt("results/k_errors.txt", k_errors)
        print("Avg Speedup ", np.mean(speedups))
        np.savetxt("results/speedups.txt", speedups)

        if include_mipod:
            print("Avg MI Eigenvector Error ", np.mean(mi_errors))
            np.savetxt("results/mi_errors.txt", mi_errors)
            print("Avg MI k Error ", np.mean(mi_k_errors) * 1e5, "pcm")
            np.savetxt("results/mi_k_errors.txt", mi_k_errors)
            print("Avg MI Speedup ", np.mean(mi_speedups))
            np.savetxt("results/mi_speedups.txt", mi_speedups)
