name: Nightly Tests

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: [self-hosted]
    strategy:
      fail-fast: false
    steps:
      - name: checkout testapp
        uses: actions/checkout@v4
      - name: checkout opensn
        uses: actions/checkout@v4
        with:
          repository: Open-Sn/opensn
          path: opensn
      - name: install opensn
        shell: bash
        run: |
          module load opensn/gcc/14 python3/3.12.3
          cd opensn && mkdir build && mkdir install && cd build 
          cmake -DCMAKE_INSTALL_PREFIX=../install .. && make -j && make install
      - name: compile app
        shell: bash
        run: |
          module load opensn/gcc/14 python3/3.12.3 libROM/1.0.0
          export OpenSn_DIR=$PWD/opensn/install
          cd ROM 
          mkdir build && cd build && cmake .. && make -j
      - name: test examples
        shell: bash
        run: |
          module load opensn/gcc/14 python3/3.12.3 libROM/1.0.0
          cd ROM
          export PYTHONPATH=$PWD/python
          cd examples/reed && python3 run_rom_reed.py --exe ../../build/rom_app_exec
